version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: angular
    ports:
      - 4200:4200
    restart: on-failure:3
    volumes:
      - .:/app:rw
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
